# Remember! When you flash custom firmware on your PanaProxy, 
# you will lose the ability to use the managed firmware updates as device 
# will no longer use the factory firmware. We will not able to know which
# entities are used, which additional ESPHome components are needed, etc.
# You will be responsible for maintaining your custom firmware, manage ESPHome Core updates, etc.
# If you want to use the managed firmware updates, you need to re-flash the factory firmware on your device. 

packages:
  panaproxy: github://IoTLabs-pl/PanaProxy/packages/panaproxy_eth.yaml@v1.0.2

# If you want to connect with HA, you need to enable API.
api:

# If you want to use OTA updates, you need to enable OTA.
ota:
  - platform: esphome

# If you want to use MQTT, you need to enable MQTT.
# mqtt:
#   broker: mqtt.example.com
#   username: !secret mqtt_username
#   password: !secret mqtt_password

# Example entities configuration.
# You can find a list of default entities on https://github.com/IoTLabs-pl/PanaProxy/tree/master/packages/default_entities
# You can also define your own entities calculated from the default ones, template entities, etc. 
sensor:
  - platform: panasonic_aquarea
    id: panaproxy_pump_flow
    top: 1
    device_id: heatpump_device
  - platform: panasonic_aquarea
    id: panaproxy_main_inlet_temperature
    top: 5
    device_id: heatpump_device

switch:
  - platform: panasonic_aquarea
    id: panaproxy_state
    set: 1
    device_id: heatpump_device
  - platform: panasonic_aquarea
    id: panaproxy_force_dhw
    set: 10
    device_id: heatpump_device