packages:
  panaproxy: !include packages/panaproxy/panaproxy.yaml
  common: !include packages/panaproxy/factory_common.yaml

improv_serial:

esp32_improv:
  authorizer: none

wifi:
  ap:
    ssid: IoTLabs PanaProxy

dashboard_import:
  package_import_url: github://IoTLabs-pl/PanaProxy/blueprint.yaml@latest
  import_full_config: true

update:
  - id: !extend ota_updater
    source: https://github.com/IoTLabs-pl/PanaProxy/releases/latest/download/manifest.json

binary_sensor:
  - id: !extend external_button
    name: Restart
    entity_category: diagnostic
    on_press:
      then:
        - lambda: id(captive_portal_).start();

sensor:
  - platform: wifi_signal
    name: RSSI
    device_id: panaproxy_device
    entity_category: diagnostic
    update_interval: 60s
