packages:
  panaproxy: !include packages/panaproxy/panaproxy.yaml
  common: !include packages/panaproxy/factory_common.yaml

improv_serial:

esp32_improv:
  authorizer: none

wifi:
  ap:
    ssid: IoTLabs PanaProxy

captive_portal:
  id: captive_portal_

dashboard_import:
  package_import_url: github://IoTLabs-pl/PanaProxy/blueprint.yaml@latest
  import_full_config: true

update:
  - id: !extend ota_updater
    source: https://ota.iotlabs.pl/PanaProxy

binary_sensor:
  - id: !extend external_button
    name: Start Captive Portal
    entity_category: diagnostic
    internal: true
    on_press:
      then:
        - lambda: id(captive_portal_).start();

sensor:
  - platform: wifi_signal
    name: RSSI
    entity_category: diagnostic
    update_interval: 60s
