sensor:
  - platform: integration
    name: "Heat Energy"
    sensor: heat_power_consumption
    time_unit: h
    restore: true
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: "kWh"
    filters:
      - multiply: 0.001
  - platform: integration
    name: "Cool Energy"
    sensor: cool_power_consumption
    time_unit: h
    restore: true
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: "kWh"
    filters:
      - multiply: 0.001
  - platform: integration
    name: "DHW Energy"
    sensor: dhw_power_consumption
    time_unit: h
    restore: true
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: "kWh"
    filters:
      - multiply: 0.001
  - platform: integration
    name: "Total Energy"
    sensor: total_consumption
    time_unit: h
    restore: true
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: "kWh"
    filters:
      - multiply: 0.001
  - platform: combination
    id: total_consumption
    name: Total Consumption
    type: sum
    state_class: measurement
    sources:
      - source: heat_power_consumption
      - source: cool_power_consumption
      - source: dhw_power_consumption
  - platform: combination
    id: total_production
    name: Total Production
    type: sum
    state_class: measurement
    sources:
      - source: heat_power_production
      - source: cool_power_production
      - source: dhw_power_production
