packages:
  version: !include version.yaml
  uart_debug: !include ../utils/uart_debug.yaml
  status_led: !include ../utils/status_led.yaml

esphome:
  name: ${ fullname | lower | replace(' ', '-') }
  friendly_name: ${ fullname }
  comment: Panasonic Aquarea Heatpump Controller
  project:
    name: IoTLabs.${ fullname }
    version: ${panaproxy_version}

external_components:
  - source:
      type: git
      url: https://github.com/IoTLabs-pl/ESPHome-Components
      ref: ${esphome_components_version}
    components:
      - panasonic_aquarea

panasonic_aquarea:
  uart_id: heatpump_uart
  external_controller_uart_id: remote_uart
