sensor:
  - platform: integration
    name: ${ name } Energy
    sensor: panaproxy_${ name | lower }_power_consumption
    time_unit: h
    restore: true
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: kWh
    device_id: heatpump_device
    filters:
      - multiply: 0.001