from pathlib import Path
from sys import path
import logging

from esphome.core import CORE
from esphome.git import clone_or_update
from esphome.yaml_util import ESPHomeDumper, dump, load_yaml

from datetime import datetime

logger = logging.getLogger(__name__)

root_dir = Path(__file__).parents[1]
packages_dir = root_dir / "packages"
target_dir = packages_dir / "default_entities"
index_file = packages_dir / "default_entities.yaml"

version_file = packages_dir / "version.yaml"
factory_firmware_file = root_dir / "factory.yaml"

fetch_head = Path(".git", "FETCH_HEAD")

components_path = Path("components")
component_path = components_path / "panasonic_aquarea"

NOTICE = 'This file is auto-generated by "scripts/default_entities.py". Do not edit manually.'
COMMENT_LINE = "# %s\n"


ESPHomeDumper.add_multi_representer(
    Path,
    lambda dumper, value: dumper.represent_scalar(
        tag="!include", value=value.as_posix()
    ),
)


def build_descriptor_name(name, prefix="panaproxy"):
    return f"{prefix} {name}".lower().replace(" ", "_").replace("-", "_")


def main():
    logger.info("Starting default_entities generation")
    logger.debug(f"Factory firmware file: {factory_firmware_file}")
    logger.debug(f"Packages directory: {packages_dir}")
    logger.debug(f"Target directory: {target_dir}")

    CORE.config_path = factory_firmware_file
    ref = load_yaml(version_file)["substitutions"]["esphome_components_version"]
    logger.info(f"ESPHome components version: {ref}")

    timestamp = datetime.now().isoformat()[:-7]
    logger.info(f"Generation timestamp: {timestamp}")

    logger.info("Cloning or updating ESPHome components repository")
    git_path, revert = clone_or_update(
        url="https://github.com/IoTLabs-pl/ESPHome-Components.git",
        ref=ref,
        refresh=None,
        domain="development",
    )
    logger.info(f"Repository path: {git_path}")
    path.insert(0, str(git_path / components_path))

    header_text = COMMENT_LINE % NOTICE
    header_text += COMMENT_LINE % f"Generated on {timestamp} from commit:"
    for line in (git_path / fetch_head).read_text().split("\t"):
        if line := line.strip():
            header_text += COMMENT_LINE % line
    header_text += "\n"

    logger.info("Loading platform descriptors")
    from panasonic_aquarea.platform_descriptor import Platform

    platforms = Platform.auto_load()
    logger.info(f"Loaded {len(platforms)} platform(s)")
    packages = {}

    for platform in platforms:
        logger.info(f"Processing platform: {platform.name}")
        target_file = Path(target_dir, platform.name).with_suffix(".yaml")
        packages[platform.name] = target_file.relative_to(index_file.parent)

        descriptor_count = len(platform._descriptors)
        logger.debug(f"Platform {platform.name} has {descriptor_count} descriptor(s)")

        with target_file.open("w") as f:
            f.write(header_text)
            f.write(
                dump(
                    {
                        platform.name: [
                            {
                                "platform": "panasonic_aquarea",
                                "id": build_descriptor_name(descriptor.name),
                                descriptor._id_field_name(): descriptor.id_value,
                                "device_id": "heatpump_device",
                            }
                            for descriptor in platform._descriptors.values()
                        ]
                    },
                )
            )
        logger.info(f"Generated {target_file}")

    logger.info(f"Writing index file with {len(packages)} package(s)")
    with index_file.open("w") as f:
        f.write(header_text)
        f.write(dump({"packages": packages}))
    logger.info(f"Generated index file: {index_file}")

    logger.info("default_entities generation completed successfully")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    try:
        main()
    except Exception as e:
        logger.error(f"Error during execution: {e}", exc_info=True)
        raise
